import { Geist, Roboto } from "next/font/google";
import "./globals.css";
import MetroNavbar from "@/shared/navbar";
import TopNavbar from "@/shared/TopNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Toshkent metropoliten | Rasmiy veb-sayt",
  description: "Generated by create next app",
  icons: {
    icon: "/logos.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${roboto.variable} antialiased`}>
        <TopNavbar />
        <MetroNavbar />
        {children}
      </body>
    </html>
  );
}
